server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/customer # this is a database we will create soon, called customer
    username: jack # have same username and password as the ones in the docker-compose.yml file
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  main:
    web-application-type: servlet